apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sjs7z5u3y-java-springboot
  janus-idp.io/tekton: sjs7z5u3y-java-springboot
  backstage.io/kubernetes-id: sjs7z5u3y-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sjs7z5u3y-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
